name: ReadAlongs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.34=ha92aebf_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h7f8727e_2
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.3=pyhc872135_0
  - python=3.10.4=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - sox=14.4.2=h93bd433_1011
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.12.0
    - asttokens==3.0.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - audioread==3.1.0
    - beautifulsoup4==4.14.3
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - chevron==0.14.0
    - click==8.1.8
    - coloredlogs==15.0.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cuda-bindings==12.9.4
    - cuda-pathfinder==1.3.3
    - cycler==0.12.1
    - datasets==4.5.0
    - debugpy==1.8.19
    - decorator==5.2.1
    - dill==0.4.0
    - docopt==0.6.2
    - et-xmlfile==2.0.0
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastapi==0.127.0
    - filelock==3.20.3
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - g2p==2.3.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==1.3.4
    - humanfriendly==10.0
    - hyperpyyaml==1.2.3
    - idna==3.11
    - ilt-editdistance==0.8.2
    - ilt-panphon==0.21.4
    - ipykernel==7.1.0
    - ipython==8.37.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.3
    - jupyter-client==8.7.0
    - jupyter-core==5.9.1
    - kiwisolver==1.4.9
    - lazy-loader==0.4
    - librosa==0.11.0
    - llvmlite==0.46.0
    - lxml==6.0.2
    - markupsafe==3.0.3
    - matplotlib==3.10.8
    - matplotlib-inline==0.2.1
    - miniaudio==1.61
    - mpmath==1.3.0
    - msgpack==1.1.2
    - multidict==6.7.1
    - multiprocess==0.70.18
    - munkres==1.1.4
    - mutagen==1.47.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numba==0.63.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.4.5
    - nvidia-nvtx-cu12==12.8.90
    - openpyxl==3.1.5
    - packaging==25.0
    - pandarallel==1.6.5
    - pandas==2.3.3
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==12.1.0
    - platformdirs==4.5.1
    - pooch==1.8.2
    - prompt-toolkit==3.0.52
    - propcache==0.4.1
    - psutil==7.1.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==23.0.0
    - pycparser==3.0
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydub==0.25.1
    - pygments==2.19.2
    - pympi-ling==1.71
    - pyogg==0.6.14a1
    - pyparsing==3.3.2
    - python-dateutil==2.9.0.post0
    - python-slugify==5.0.0
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - readalongs==1.2.1
    - regex==2025.11.3
    - requests==2.32.5
    - ruamel-yaml==0.18.17
    - ruamel-yaml-clib==0.2.15
    - safetensors==0.7.0
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - semver==3.0.4
    - sentencepiece==0.2.1
    - setuptools==80.9.0
    - shellingham==1.5.4
    - six==1.17.0
    - soundfile==0.13.1
    - soundswallower==0.6.5
    - soupsieve==2.8.1
    - soxr==1.0.0
    - speechbrain==1.0.3
    - stack-data==0.6.3
    - starlette==0.50.0
    - sympy==1.14.0
    - text-unidecode==1.3
    - threadpoolctl==3.6.0
    - tokenizers==0.22.2
    - torch==2.10.0
    - torchaudio==2.10.0
    - tornado==6.5.4
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==5.0.0
    - triton==3.6.0
    - typer-slim==0.21.1
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - unicodecsv==0.14.1
    - urllib3==2.6.2
    - wcwidth==0.2.14
    - webvtt-py==0.4.2
    - wheel==0.45.1
    - xxhash==3.6.0
    - yarl==1.22.0
prefix: /home/mila/g/guzmand/scratch/.conda/envs/ReadAlongs

